# -----------------------------
# Environment Definition
# -----------------------------
environments:
  dev:
    values:
      - environments/dev.yaml

---

# -----------------------------
# Repositories
# -----------------------------
repositories:
  - name: helm-openldap
    url: https://jp-gouin.github.io/helm-openldap/

---

# -----------------------------
# Releases
# -----------------------------
releases:
  - name: openldap
    namespace: ldap
    chart: helm-openldap/openldap-stack-ha
    installed: true
    createNamespace: true
    values:
      - persistence:
          enabled: true
          size: 2Gi
      - openldap:
          adminPassword: "ChangeMe123!"  # For production, replace with a sealed secret
          baseDN: "dc=example,dc=org"
          replication:
            enabled: false
      - service:
          type: ClusterIP
      - resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
