# -----------------------------
# Environment Definition
# -----------------------------
environments:
  dev:
    values:
      - environments/dev.yaml

---

# -----------------------------
# Repositories
# -----------------------------
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

---

# -----------------------------
# Releases
# -----------------------------
releases:
  - name: demo-nginx
    namespace: default
    chart: bitnami/nginx
    installed: false
    values:
      - service:
          type: NodePort
