apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freeradius.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "freeradius.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "freeradius.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "freeradius.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: freeradius
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: auth
              containerPort: {{ .Values.service.ports.auth }}
              protocol: UDP
            - name: acct
              containerPort: {{ .Values.service.ports.acct }}
              protocol: UDP
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: freeradius-config
              mountPath: /etc/freeradius/3.0/mods-available/ldap
              subPath: mods-available-ldap
            - name: freeradius-config
              mountPath: /etc/freeradius/3.0/mods-enabled/ldap
              subPath: mods-available-ldap
      nodeSelector:
    {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
    {{ toYaml .Values.tolerations | nindent 8 }}
      affinity:
    {{ toYaml .Values.affinity | nindent 8 }}
      volumes:
        - name: freeradius-config
          secret:
            secretName: {{ include "freeradius.fullname" . }}-ldap-secret
            items:
              - key: mods-available-ldap
                path: mods-available-ldap
