apiVersion: v2
name: openldap
description: "Wrapper chart for the OpenLDAP stack used in this project"
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: openldap-stack-ha
    version: ">=0.0.0-0"
    repository: "https://jp-gouin.github.io/helm-openldap/"
